modLoader="javafml"
loaderVersion="[4,)"
license="Apache License version 2.0"

[[mods]]
modId="vein_vantage"
version="2.0.8"
displayName="Vein Vantage"
displayURL="https://github.com/Dreyka-Oas/VeinVantage.git"
logoFile="logo.png"
credits="O.A.S"
authors="Dreyka Oas"
description="Better Mining"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.vein_vantage]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.94-beta,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.vein_vantage]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration